### ISSUE TITLE
@captcha($lang = null) ignores all input fields width required

### ISSUE THREAD

**Issue by BAKTETE** [albertcht/invisible-recaptcha#13]
`<input type="text" value="{{ old('email') }}" name="email" placeholder="Email *" class="form-control input-md form-group" required> `

`@captcha($lang = null)` submit form directly without taking the required fields in consideration

**Comment by albertcht** [comment]
This is because the submit button will be bound to a recaptcha function via click listener once rendered. In recaptcha function there's a preventDefault() so it skips javaScript validation API directly.
In the commit [4257a97](https://github.com/albertcht/invisible-recaptcha/commit/4257a9726f03b07cb7a27fc861ed9568939b4314), this bug should be fixed because I change the binding listener to a submit action. You can try it again with this commit.

**Comment by BAKTETE** [comment]
it's working now thank you for this amazing package

**Comment by albertcht** [comment]
You're welcome ^^
