### ISSUE TITLE
Upgrading from 7 to 8 failed 

### ISSUE THREAD

**Issue by realanmup** [albertcht/invisible-recaptcha#143]
While upgrading to laravel 8 i got stuck on due to this package, i removed and tried it works.

**Comment by realanmup** [comment]
https://github.com/albertcht/invisible-recaptcha/pull/142

**Comment by walidbagh** [comment]
@realanmup 

@albertcht appears to have abandoned the project sadly so I doubt this'll be merged. Several prominent projects that relied on it have now moved to alternatives so that might be the best course of action.

_Originally posted by @rickmills in https://github.com/albertcht/invisible-recaptcha/issues/138#issuecomment-732129844_
