### ISSUE TITLE
A way to hide the site key

### ISSUE THREAD

**Issue by dcaldessa** [albertcht/invisible-recaptcha#15]
Greetings, 

I am using your package in my laravel project it is working great. But I do have one question is there a way to hide the site key from inspection. Cause when I inspect my registration page using google chrome I can see my sitekey there, and well do you really want it to be known to the whole world? So that is why I am asking if there is a way to encode or hide it from view?..

thanks 

dcaldessa.

**Comment by albertcht** [comment]
There's no need to hide your site key at all because it is designed to be public. Someone who stole 
 your site key can't do anything. You need to use your the other secret key to validate the captcha response. And your secret key is stored on your server side. It's safe.
You can also go to the admin console and set your domain to the whitelist. In that way, your captcha  can only be rendered on your domains.

**Comment by ConsciousState** [comment]
> There's no need to hide your site key at all because it is designed to be public. Someone who stole
> your site key can't do anything. You need to use your the other secret key to validate the captcha response. And your secret key is stored on your server side. It's safe.
> You can also go to the admin console and set your domain to the whitelist. In that way, your captcha can only be rendered on your domains.

That is not true.
Services like DeathByCaptcha, 2captcha etc requires a sitekey to complete a recaptcha for you and automating recaptcha protected sites...

**Comment by rameshna2004** [comment]
Is there any other way to hide site key?

**Comment by Safeer-Abbas** [comment]
lol i need to find the site key on a site that hid the site key >.>

**Comment by Safeer-Abbas** [comment]
and i found it :>

**Comment by lloydtawanda** [comment]
The sitekey is meat to be public
