### ISSUE TITLE
Double form submit

### ISSUE THREAD

**Issue by leiiinad** [albertcht/invisible-recaptcha#33]
Hi.

I have included recaptcha and trying submit form with ajax, but recaptcha ignore them and submit form with URL. Do you know how fix this?

**Comment by albertcht** [comment]
Hi @leiiinad , did you implement `_submitEvent` function to call your ajax action?

**Comment by leiiinad** [comment]
Yes, i have submit event.

`item.submit(function(e) {});`

**Comment by albertcht** [comment]
Can you provide your full script how you trigger your ajax call? Otherwise I don't have enough info to figure it out, thanks!

**Comment by leiiinad** [comment]
Yes, sure.

This is form example:
`{!! Form::open(['name' => 'registration-form', 'url' => '', 'id' => 'registration-form', 'data-ajax-form' => 'true']) !!}`

...and submit button:
`<button type="submit" class="btn">Submit</button>`

In this form call i recaptcha:
`@captcha()`

I have custom js script to dynamic create ajax call.
For example:

`$('form[data-ajax-form=true]').submit(function(e) {
	e.preventDefault();
	
	$.ajax({
		type: "POST",
		url: url,
		data: data,
		dataType : 'json',
		beforeSend: function() {},
		success: function(r) {},
		error: function(jqXHR, textStatus, errorThrown) {}
	});
});`

**Comment by leiiinad** [comment]
The problem is because recaptcha submit form and not make validation with Laravel validator on submit general form.

**Comment by albertcht** [comment]
All your customized action needs to be implemented in `_submitEvent` function. So your js code should look like:
```
_submitEvent = function() {
    $.ajax({
		type: "POST",
		url: url,
		data: data,
		dataType : 'json',
		beforeSend: function() {},
		success: function(r) {},
		error: function(jqXHR, textStatus, errorThrown) {}
	});
};
```

**Comment by leiiinad** [comment]
I get an error:
`Uncaught ReferenceError: _submitEvent is not defined`

Why this not work with classic ajax call implementation?

**Comment by albertcht** [comment]
Please turn on the debug mode by setting `INVISIBLE_RECAPTCHA_DEBUG=true` in .env file to check if your render is correct. If any of these bindings is false, that means you render the captcha in a wrong place.
If you render this captcha correctly, it will listen to the submit event to bind validation automatically. This is why you need to implement `_submitEvent` to do your customized action in this function instead of binding the submit event by yourself, otherwise it will not trigger the captcha validation.

**Comment by leiiinad** [comment]
All bindings are true...

```
Checking element binding of _submitForm...
true
Checking element binding of _captchaForm...
true
Checking element binding of _captchaSubmit...
true
```

**Comment by albertcht** [comment]
ok, I think you're almost there. Let's clarify your issues now...
1. Does error `Uncaught ReferenceError: _submitEvent is not defined` still exist?
2. Does your original issue `recaptcha ignore ajax and submit form with URL` still exist?
3. Do you call your ajax action successfully now?

**Comment by leiiinad** [comment]
- Does error `Uncaught ReferenceError: _submitEvent is not defined` still exist?
**No, besause i don't used in my custom ajax.**
- Does your original issue` recaptcha ignore ajax and submit form with URL` still exist?
**Yes.**
- Do you call your ajax action successfully now?
**Both action are called...my ajax and recaptcha submit form with URL. There is the problem, because recaptcha submit form ignore ajax call.**

**Comment by albertcht** [comment]
well... I just created a repo for demonstrating how to use this package with ajax. It works fine.
Please see: https://github.com/albertcht/invisible-recaptcha-example

**Comment by leiiinad** [comment]
Yes, in this case works fine. I will clone your repo and edit with my example. Give me some time.

**Comment by leiiinad** [comment]
Check my fork.

**Comment by albertcht** [comment]
There's only one principle when you customized your own submit function: 
**do it in `_submitEvent ` function**
So just try to trigger your ajax call in that function, and do not bind the submit event by yourself.
If you think it limits your code structure, you can refer to https://developers.google.com/recaptcha/docs/invisible to implement original api in the frontend rather than render captcha provided by this package.
The backend validation still works in this case.

**Comment by marcelogarbin** [comment]
@albertcht one question i'm facing, does the "_submitEvent" function only work with ajax?
