### ISSUE TITLE
1.7 breaks load of Blade directives for other packages

### ISSUE THREAD

**Issue by BAKTETE** [albertcht/invisible-recaptcha#41]
please consider making changes in `InvisibleReCaptchaServiceProvider.php ` in `register()` method
```
-        $this->app->resolving('view', function () {
+        $this->app->resolving('blade.compiler', function () {
```
@albertcht 
the conflict happens with `spatie/laravel-permission `
For more informations 
[Blade extensions are not registered and output as text in boot #458](https://github.com/spatie/laravel-permission/issues/458)
[LaravelCollective/html#330](https://github.com/LaravelCollective/html/issues/330)

**Comment by albertcht** [comment]
hi @BAKTETE , thanks for your suggestion, but I have no clues how it breaks other packages at this moment. Do you mind giving an example or explanation?  thank you!

**Comment by rossbearman** [comment]
Hi @albertcht,

I think I can shed some light on this. Currently you're registering Blade directives while some service providers are still being registered, by only waiting until the `view` provider is resolved. Ideally you would register the Blade directives [during the `boot()` method](https://laravel.com/docs/5.5/blade#extending-blade), rather than `register()`. Alternatively waiting for `blade.compiler` to be resolved may work, but that may just make it conflict with different packages.

**Comment by albertcht** [comment]
hi @BAKTETE @rossbearman, really appreciated your information. I will work on this issue as soon as possible.

**Comment by albertcht** [comment]
changed to `$this->app->afterResolving('blade.compiler'` in v1.7.1
